export const EMPTY_PREVIEW = 'http://localhost:5274'
export const rows = '[data-slot="data-list-row"]'
export const badge = '[data-sidebar="menu-badge"]'
export const sidebarContent = '[data-sidebar="content"]'
export const applicationCards = '[data-slot="application-cards"]'
export const serviceRows = '[data-slot="service-list"] [data-slot="data-list-row"]'
